### ISSUE TITLE
白板和音视频录制时长不一时如何处理？

### ISSUE THREAD

**Issue by CloudTsang** [netless-io/netless-combine-player#23]
我的产品在会同时开启白板和通讯录制，而音视频通讯的录制视频比白板录制视频慢了数秒的（大概是）摄像头启动时间。
重播时内容会稍微错开，同时通讯视频先播放结束便触发了停止播放的方法，导致白板最后数秒播不出来。
这是我升级sdk后测试出来的情况，不清楚是不是代码上还有需要注意修改的地方。
请问这样的情况有什么对齐两个视频的方法吗？

**Comment by BlackHole1** [comment]
这个在设计 `combine-player` 的时候就是这么考虑的，当有一端播放结束后，就会暂停所有端。

如果是需要有一端播放结束后，不触发暂停，继续播放，在代码层面上是可以实现的。

由于 摄像头 需要启动，出现的时间差，导致重播内容会错开，这个问题只能从业务层面上避免，因为我们无法知道错开的时间差是多少。

业务层面上，你可以等待摄像头加载好之后，再真正的认为开始上课/录制
